version: '3.13'

services:
  reservation_calender:
    image: reservation_calender:latest
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@postgres:5432/reservation_db
    depends_on:
      - postgres
      - frontend
  
  frontend:
    image: node:20
    restart: unless-stopped
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: ["yarn", "dev"]
  
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: reservation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: