name: Reservation-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Lint
        run: |
          cd frontend
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn lint

  Backend:
    runs-on: ubuntu-latest
    needs: Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.0"

      - name: Install dependencies
        run: |
          python3 --version && \
          python3 -m pip install --no-cache-dir --upgrade pip poetry && \
          python3 -m pip --version && \
          poetry config virtualenvs.in-project true && \
          poetry install --no-root --with dev

      - name: Lint code
        run: |
          source .venv/bin/activate && \
          poetry run black --check .

      - name: Run unit test
        run: poetry run pytest -v

  Build-and-Push-image:
    runs-on: ubuntu-latest
    needs: Backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push using build.sh
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          chmod +x ./build.sh
          ./build.sh --push --ci
